#' KEGGenrich
#'
#'Analyse RNA-seq data
#' @param GENE_TO_ENRICH gene list generated by IDchange
#' @param CHANGEtoTYPE type of gene
#' @param SPECIES specie
#' @example
#' KEGGenrich(GENE_TO_ENRICH,SPECIES)
KEGGenrich<-function(x,SPECIES){
  species_list<-c("HUMAN","MOUSE","RAT")
  if (!SPECIES%in%species_list) {
    ERRORinSPECIES<-paste("input should be one of",paste(species_list,collapse = ","))
    stop('"SPECIES"', ERRORinSPECIES)
  }
  if (SPECIES=="HUMAN") {
    OrgDb="org.Hs.eg.db"
    KEGG_database="hsa"
  }
  if (SPECIES=="MOUSE") {
    OrgDb="org.Mn.eg.db"
    KEGG_database="mmu"
  }
  if (SPECIES=="RAT") {
    OrgDb="org.Rn.eg.db"
    KEGG_database="rno"
  }
  KEGG<-clusterProfiler::enrichKEGG(x,
                                    organism = KEGG_database,
                                    pvalueCutoff = 0.05,#设定p值阈值
                                    qvalueCutoff = 0.05,#设定q值阈值
  )
  KEGG_readable<-DOSE::setReadable(KEGG,
                                   OrgDb = OrgDb,
                                   keyType = "ENTREZID")
  return(KEGG_readable)
}
